### PR TITLE
style: fix some style issues, core code intact

### PR DESCRIPTION
**Pull request by k4black**
### Summary

Code style fix, mostly black formatting, `cer.py` file, and small issues (e.g. typings mismatch)

## Changes 

* Apply `isort` and `black` formatting
* For the cer.py file:
  - Refactor docstrings to pep8 format
  - Refactor comments to pep8 format
* Add empty last line according to pep8
* Remove reluctant brackets, e.g. `yield (start_1, start_2, length)`
* Fix some typing errors, but further typing is needed
* Rename Shadows built-in names, e.g. `input` -> `_input`

Moreover: 
* fix `numpy` version <1.19.5,  as `simalign` is not compatible with numpy >=1.20.0 (np.int is deprecated), while 1.19.5 vulnerable

### CODE REVIEW

**Comment by gsarti** [comment]
Thanks for the PR! Can we also get a minimal Makefile with a `fix-style` command for reapplying the `black` and `isort` checks you ran on new code? Thanks in advance!

**Comment by k4black** [comment]
@gsarti At the moment the black and isort is applied:
```
All done! ✨ 🍰 ✨
7 files left unchanged.
```
and empty output for isort

**Comment by gsarti** [comment]
Thanks for checking! I actually meant to create a `Makefile` in the root folder (see [here](https://github.com/inseq-team/inseq/blob/main/Makefile) for an example) to be able to call `make fix-style` in command line to run black and isort checks!

P.S. I advise to drop `isort` altogether and just use [`ruff`](https://github.com/charliermarsh/ruff) with `black` like we do in Inseq, since it does `isort` and `flake8` job at a fraction of the time!

**Comment by k4black** [comment]
> Thanks for checking! I actually meant to create a `Makefile` in the root folder (see [here](https://github.com/inseq-team/inseq/blob/main/Makefile) for an example) to be able to call `make fix-style` in command line to run black and isort checks!

Oh, sorry, I referred to the [existing Makefile](https://github.com/gsarti/divemt/blob/572d69f6ce2b6bcc746e1e4f26cfeba2514b3156/Makefile#L12)

I'll update it with `ruff`

**Comment by gsarti** [comment]
Didn't realize we already had one, sorry and thanks for pointing that out! :sweat_smile: If you could update it with ruff would be great, thanks!

**Comment by k4black** [comment]
@gsarti Please check, also moved metadata to the `pyproject.toml`, anyway needed to create one

**Review by gsarti — APPROVED** [review]
Good to go!

**Pull request merged**
